### ISSUE TITLE
Glossary: Variable mutation doesn't make the distiction of mutation vs. reassignment

### ISSUE THREAD

**Issue by senocular** [mbeaudru/modern-js-cheatsheet#1]
In [variable mutation](https://github.com/mbeaudru/modern-js-cheatsheet#-variable-mutation): 

```
var myVar = "Nick";
myVar = "John" // here myVar is being mutated
```

Though this is a reassignment, not a mutation, a distinction that is made in [Notions: Variable declaration](https://github.com/mbeaudru/modern-js-cheatsheet#short-explanation).

It should say myVar is said to be reassigned (variables are assigned, values are mutated).

**Comment by mbeaudru** [comment]
Thanks a lot!

This is absolutely correct so I will just remove this wrong sample from the glossary since [only arrays and objects can be mutated](https://developer.mozilla.org/en-US/docs/Glossary/Mutable).
