### ISSUE TITLE
Constants are not variables

### ISSUE THREAD

**Issue by nekromoff** [mbeaudru/modern-js-cheatsheet#103]
And therefore, calling `const` variables is just plain wrong. Whole section in variables refers to them this way.

Also, telling someone to declare their variable as `const` is just completely incorrect based on any programming principles. That might be your preference and opinion, but it's definitely not based on any programming books or recommendations.

I haven't got to read the rest, so far, but if this issue is right in the beginning, I don't want to know, what else is lurking in your `manual`.

**Comment by GMaiolo** [comment]
ES6 `const` is not about value immutability, but immutable _binding_.

**Comment by mbeaudru** [comment]
Hi @nekromoff ,

I understand that you aren't fond of the way things are written and that's okay, there are options:

* Suggest another formulation in this issue
* Propose a pull request

Besides, I'm just *recommanding* to use `const` by default and `let` when there is a biding change. More to that, I'm warning the reader right at the beginning of the document

> I will sometimes provide personal tips that may be debatable but will take care to mention that it's a personal recommendation when I do so.

And for the last part, if you don't like this repo and don't want to read more that's fine. Now if you really want things to be better you can do like others and contribute :+1: .

I will reopen this issue if there are better propositions that what's currently in the document, until then it's closed.
