### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by LeonidHr** [mbeaudru/modern-js-cheatsheet#134]

**Comment by Rafaeltaichicoach** [comment]
Hello friend. I will be here to still communicating between us, okay?

**Comment by Rafaeltaichicoach** [comment]
> 

I want to share with you another development project, it is the heart of the Microverse and its very important for all of us, financially talking.

https://www.btcs.love/invite/3p8gv

Just download it to your laptop. Then I will guide you to obtain capital for profits!
[Screenshot_20220506-005801.jpg](https://user-images.githubusercontent.com/91766354/167079176-a4159db8-2308-4611-8806-16be5535f49e.jpg)
