### ISSUE TITLE
'let' and 'const' get hoisted

### ISSUE THREAD

**Issue by errorsmith** [mbeaudru/modern-js-cheatsheet#18]
Declarations get hoisted, including `let` and `const`.

From the [documentation](https://tc39.github.io/ecma262/#sec-let-and-const-declarations):

> ### 13.3.1 Let and Const Declarations
> 
> let and const declarations define variables that are scoped to the running execution context's LexicalEnvironment. **The variables are created when their containing Lexical Environment is instantiated but may not be accessed in any way until the variable's LexicalBinding is evaluated**. A variable defined by a LexicalBinding with an Initializer is assigned the value of its Initializer's AssignmentExpression when the LexicalBinding is evaluated, not when the variable is created. If a LexicalBinding in a let declaration does not have an Initializer the variable is assigned the value undefined when the LexicalBinding is evaluated.

So variables declared with `let `and `const` are created when accessing the enclosing scope, but remain **uninitialized** until the code containing the actual declaration is executed.

The TDZ article linked in this cheatsheet is also mentioning this.

**Comment by mbeaudru** [comment]
Hi @errorsmith, thanks for pointing this out because I indeed made a mistake here. I'll notice when fixed 👍
