### ISSUE TITLE
Code blocks not closed/opened properly

### ISSUE THREAD

**Issue by Spruudel** [mbeaudru/modern-js-cheatsheet#20]
Lots of unwanted stuff happening after line 144.

**Comment by mbeaudru** [comment]
I'm sorry but I don't understand what you mean here. Can you be more precise and point me to a specific example ?

**Comment by Spruudel** [comment]
Seems to be a problem within the OctoDroid app I use. 
Viewing the file in the browser, I'm unable to find any problems.
In the App this:
> ```var``` and ```let ``` are about the same, but ```let``` declared variables

looked like
> var ```and``` let ``` are about the same, but ```let``` declared variables
