### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by soyaine** [mbeaudru/modern-js-cheatsheet#22]
Bonjour! Can I translate your modern-js-cheatsheet into Chinese, by pulling request a new file named readme_CN.md to your repo? Or any other way is ok. 😁😁

**Comment by mbeaudru** [comment]
Hi @soyaine ! Yes I encourage you to do so, it would be nice.

Someone has suggested the same before you, [check my answer for more details on the procedure](https://github.com/mbeaudru/modern-js-cheatsheet/issues/15).

Thanks ! 💯

**Comment by soyaine** [comment]
Hhhh~ Fine

**Comment by mbeaudru** [comment]
I'm closing this one so that we can focus on this topic on the same issue ticket :+1:
