### ISSUE TITLE
Missing yield and generators

### ISSUE THREAD

**Issue by AaronNGray** [mbeaudru/modern-js-cheatsheet#27]
Missing **yield** keyword and generators

Advanced example :- Tree walking 
```
function * elements (tree) {
  yield tree.label;
  if (tree.children)
    for (const child of tree.children)
      yield * elements(child);
}

[...elements(tree)]
  //=> [ 1, 2, 4, 5, 3, 6]
```
http://raganwald.com/2016/11/30/anamorphisms-in-javascript.html

**Comment by yaronuliel** [comment]
You meant _yield_ :)

**Comment by mbeaudru** [comment]
I'm on it, planned for today delivery :wink: thanks for the suggestion

**Comment by catdaddy23** [comment]
hey,  I new

**Comment by mbeaudru** [comment]
Oops, didn't had time to do this as I planned 😅, personal stuff happened. If someone wants to PR on this, do it 👍 otherwise I will do it when I can.
