### ISSUE TITLE
Set up a jekyll theme and publish on gh-pages

### ISSUE THREAD

**Issue by anshumanv** [mbeaudru/modern-js-cheatsheet#28]
This will probably improve the view of the document and will allow sharing with ease.

**Comment by mbeaudru** [comment]
Good idea! I will think about it :+1:

**Comment by anshumanv** [comment]
Appreciate it, just need to switch to settings tab and select appropriate theme !

Anyways keeping this issue open, close it when you come up with a decision :+1:

**Comment by mbeaudru** [comment]
Wow ! Didn't realized it was this easy :sweat_smile: , [check it out!](https://mbeaudru.github.io/modern-js-cheatsheet/)

**Comment by anshumanv** [comment]
Splendid ! @mbeaudru looks awesome than ever !
Happy to see this little suggestion getting implemented :smile:
