### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by ericloong90** [mbeaudru/modern-js-cheatsheet#4]
Hi,

Found a spelling error at both markdown files, introduction>motivation second and third paragraph. 

<img width="888" alt="screen shot 2017-09-19 at 10 18 17 am" src="https://user-images.githubusercontent.com/11158076/30573007-e4e1c254-9d23-11e7-83cf-ea826ea3a999.png">

Developers, not `developpers`. Recommendation, not `recommandation`. Could be more, just skimmed through the first few parts. 

Great job at the cheatsheet by the way.

**Comment by mbeaudru** [comment]
Thanks ! This has been fixed by a contributor 👍 : [see pull request](https://github.com/mbeaudru/modern-js-cheatsheet/pull/2)
