### ISSUE TITLE
Fold detailed explanations

### ISSUE THREAD

**Issue by hontas** [mbeaudru/modern-js-cheatsheet#44]
It's a long document, and maybe a bit more text than I would expect of a cheatsheet ;) so it would be nice to use githubs folding syntax for all detailed explanations like so:

```
<details>
  <summary>Click to expand</summary>
  whatever
</details>
```

**Comment by mbeaudru** [comment]
I had to take a step back on the folding because it was [breaking the website](https://github.com/mbeaudru/modern-js-cheatsheet/issues/50)
