### ISSUE TITLE
named exports

### ISSUE THREAD

**Issue by ghost** [mbeaudru/modern-js-cheatsheet#48]
Hi, on modules you write:

> You can only name-export variables (**not functions or class**), so if you want to name-export a function, you have to store it in a variable before.

But on one of the examples on [MDN ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)I can see a function `cube `being directly exported (as opposed to what you said above that you can't export it directly):

```
// module "my-module.js"
function cube(x) {
  return x * x * x;
}
const foo = Math.PI + Math.SQRT2;
export { cube, foo };
```

Can you clarify this?

**Comment by mayank-mittal** [comment]
I think he meant to say , you can't export anonymous functions. you cannot export like `export {function(){....}}`

or `export {function cube(x){return x*x*x}}`

So you are stuck with 

either `const cube = function(x){return x*x*x}; export {cube}`
or `function cube(x){return x*x*x}; export {cube}`

**Comment by mbeaudru** [comment]
Indeed, this needs to be clarified. I will update the documentation to indicate that anonymous function can't be *name-exported* but that named functions can.

Thanks for the catch!
