### ISSUE TITLE
Udacity Course for Javascript

### ISSUE THREAD

**Issue by hkasera** [mbeaudru/modern-js-cheatsheet#65]
Hello,

I would like to raise a PR to add the [Udacity course](https://www.udacity.com/course/javascript-basics--ud804) for Javascript under [Complementary Resources](https://github.com/mbeaudru/modern-js-cheatsheet#complementary-resources) section. I believe this course is really useful.

Let me know if this sounds good, I will raise a PR for the same.

Regards,
Harshita Kasera

**Comment by mbeaudru** [comment]
Hi @hkasera ! It is a good idea, but someone saw this issue you raised and [did the PR for you](https://github.com/mbeaudru/modern-js-cheatsheet/pull/66).

I gladly accepted it 👍.

If you have other ideas in mind, don't hesitate 😉.

Thank you!

**Comment by hkasera** [comment]
Thanks for acknowledging and updating me!
I prefer to raise an issue before sending PR so I can get a confirmation with the maintainers. I guess not everyone does that. Anyways thanks for letting me know!
