### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by ajbrzoz** [mbeaudru/modern-js-cheatsheet#90]
Hi, I'm a pythonista who's been tinkering with JavaScript a lot lately and I would love to translate your amazing guide into Polish. I'm already halfway through.

**Comment by tborowy** [comment]
@ajbrzoz great, I sometimes wondered if i did translate it but lack of time and poor language knowledge did not push me to that;)

**Comment by mbeaudru** [comment]
@ajbrzoz Thanks ! Translations are always welcomed 👍
