### ISSUE TITLE
Translations branches

### ISSUE THREAD

**Issue by tborowy** [mbeaudru/modern-js-cheatsheet#97]
I wonder if it would be better if every translation had its have branch in the commit tree. In case of updating master branch, it was easier to make corrections to translations.

**Comment by mbeaudru** [comment]
You can look for the *main* [README.md commit history](https://github.com/mbeaudru/modern-js-cheatsheet/commits/master/README.md) to know what has changed in it, without the translation commits.

But yeah, it's not very simple for translations to keep on sync with the main version and I see no better way to do it.
